/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#ffdec5",
        "surface": "#131313",
        "tertiary": "#ffb869",
        "outline-variant": "#3e484f",
        "on-secondary-fixed-variant": "#6c3a00",
        "tertiary-fixed-dim": "#ffb869",
        "primary-fixed": "#c2e8ff",
        "primary": "#75d1ff",
        "outline": "#889299",
        "on-tertiary-fixed": "#2b1700",
        "tertiary-container": "#e29432",
        "primary-container": "#3ab0e2",
        "inverse-on-surface": "#303030",
        "background": "#000000",
        "on-tertiary": "#482900",
        "on-primary": "#003548",
        "secondary-fixed-dim": "#ffb778",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#bdc8d0",
        "secondary-fixed": "#ffdcc1",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "surface-tint": "#75d1ff",
        "surface-container-low": "#1b1b1b",
        "surface-container": "#1f1f1f",
        "secondary": "#C8811A",
        "on-primary-fixed": "#001e2b",
        "on-tertiary-container": "#573200",
        "on-error": "#690005",
        "on-background": "#e2e2e2",
        "surface-variant": "#353535",
        "on-secondary": "#4c2700",
        "surface-container-highest": "#353535",
        "on-primary-container": "#004056",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "on-surface": "#e2e2e2",
        "on-secondary-fixed": "#2e1500",
        "secondary-container": "#995400",
        "primary-fixed-dim": "#3AB0E2",
        "on-primary-fixed-variant": "#004d67",
        "surface-bright": "#393939",
        "on-tertiary-fixed-variant": "#673d00",
        "tertiary-fixed": "#ffdcbb",
        "inverse-surface": "#e2e2e2",
        "inverse-primary": "#006688"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
